### ISSUE TITLE
[Feature request] Add "exclusions" for backing up local folders

### ISSUE THREAD

**Issue by hoggatt** [gromoslaw-kroczka/home-server-backup#20]
This is a nice looking backup script! It would be awesome if you were able to add a "local exclusions" array to your parameters script. 

For example, I have a photo cache in my home directory that I don't want to back up and it takes up a lot of space. It would be nice if I could specify a list of folders I don't want to be backed up.

**Comment by gromoslaw-kroczka** [comment]
Thank you @hoggatt for that idea! I'm just adding this feature as requested and will add to master branch right away.

**Comment by hoggatt** [comment]
This looks awesome, thanks! I'm gonna start using it now.
